system: "base16"
name: "Metal Gear Rising Battle"
palette:
  base00: "10161a"
  base01: "151c22" 
  base02: "1d262d"
  base03: "2f3b46"
  base04: "50616b"
  base05: "a8bbc3"
  base06: "cbdce1"
  base07: "e6f0f3"
  base08: "df341a"
  base09: "e3523d"
  base0A: "40d8ce"
  base0B: "a6b7bd"
  base0C: "58ecff"
  base0D: "2f88ff"
  base0E: "7f4dff"
  base0F: "bd3a2e"
